### ISSUE TITLE
Wrong fold method set after ^Wo

### ISSUE THREAD

**Issue by gi1242** [Konfekt/FastFold#18]
Hi There,

Thanks a lot for this -- it makes vim usable on long TeX papers!

I found a possible bug: When I split the window (e.g. with :copen), jump to the quickfix window, return to the main window and press "^Wo" (i.e. close the quick fix window) then I find that my foldmethod is set back to syntax.

Can you reproduce it? The fold settings I use are:

    nmap <SID>(DisableFastFoldUpdate) <Plug>(FastFoldUpdate)
    let g:fastfold_fold_command_suffixes =  ['x','X']
    let g:fastfold_fold_movement_commands = []
    let g:fastfold_savehook = 0

Thanks,

GI

**Comment by Konfekt** [comment]
Thanks! That's no coincidence; this plugin exists because I found folding to slow Vim down to a crawl when using TeX with syntax folding and concealing. 

I guess this occured because the `BufWinLeave` autocmd, when leaving the quickfix window, set the foldmethod in the buffer being switched to instead of that getting closed.

Since it only existed for `restore_view.vim` but `vim-stay` handles this more robustly anyway, I just disabled it. 

It should no longer occur.  Can you confirm?

**Comment by gi1242** [comment]
Yep, fixed. Thanks for the quick response :)
