### ISSUE TITLE
Is it possible to avoid ':windo' in BufWinEnter?

### ISSUE THREAD

**Issue by mMontu** [Konfekt/FastFold#65]
I've noticed that sometimes FastFold changes my window layout.
By disabling the save hook (`let g:fastfold_savehook = 0`) the frequency of the issue has decreased.

But the issue still happens in the following scenario:

* In a tabpage containing multiple vertical splits, run [`CTRL-W_bar`](http://vimhelp.appspot.com/windows.txt.html#CTRL%2dW_bar)
* edit a new file: `:e abc`

This seems to happen due to the [BufWinEnter in L215](https://github.com/Konfekt/FastFold/blob/master/plugin/fastfold.vim#L215) which triggers the [s:Windo() calls](https://github.com/Konfekt/FastFold/blob/master/plugin/fastfold.vim#L106), since it also happens by running `:windo` direclty after the <kbd>Ctrl</kbd>-<kbd>W</kbd>+<kbd>|</kbd>.

I've been reading the plugin code but I still don't understand it completely. In speciall, why is it necessary to call `s:LeaveWin()` and `s:EnterWin()` in all the windows, since the [command seems to execute only in the current buffer](https://github.com/Konfekt/FastFold/blob/master/plugin/fastfold.vim#L105)?

```
  let s:curbuf = bufnr('%')
  call s:WinDo("if bufnr('%') is s:curbuf | call s:LeaveWin() | endif")
  call s:WinDo("if bufnr('%') is s:curbuf | call s:EnterWin() | endif")
```
I thought it'd be because of autocommands, but since the calls to `execute` inside `s:Windo()` contains `noautocmd` I'm out of ideas.

**Comment by Konfekt** [comment]
> why is it necessary to call s:LeaveWin() and s:EnterWin() in all the windows, since the command seems to execute only in the current buffer?

While in practice usually there is only one window for a buffer, in theory there can be many windows and folding is done per window, not buffer. This said, in practice it proved useful to assume the same folding method `&fdm` in all windows. Still, if something changes in the buffer, all windows need to be updated.

> This seems to happen due to the BufWinEnter in L215 which triggers the s:Windo() calls, since it also happens by running :windo direclty after the Ctrl-W+|.

>    In a tabpage containing multiple vertical splits, run CTRL-W_bar edit a new file: :e abc
> This seems to happen due to the BufWinEnter in L215 which triggers the s:Windo() calls, since it also happens by running :windo direclty after the Ctrl-W+|.

Yes, reproducible and true, it is due to the `windo` calls.

The `s:windo()` function already tries to [preserve](https://github.com/Konfekt/FastFold/blob/066d2347baa8dc180c18f889d0b37a826f23973b/plugin/fastfold.vim#L80) much of what `window` does not preserve, but I am afraid saving the window layout state would bog down Vim disproportionately.

Therefore, would you mind asking at [Vim](github.com/vim/vim/issues/) first, if this is how things are meant?

**Comment by Konfekt** [comment]
This is, the change of window layout by `windo` seems to occur only after `Ctrk-W |` and not otherwise. This seems unintended.

**Comment by mMontu** [comment]
Thanks for the quick reply! 

> While in practice usually there is only one window for a buffer, in theory there can be many windows and folding is done per window, not buffer. 

I didn't think of that, but sure, it makes sense.

> Therefore, would you mind asking at Vim first, if this is how things are meant?

It was a good idea to check in the Vim project first: there is already [an issue](https://github.com/vim/vim/issues/4622) about this, and also a workaround.

I'll create a PR updating `s:WinDo()`.

**Comment by mMontu** [comment]
@Konfekt thanks again!!
